//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ali_Diplom.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public int ID { get; set; }
        public int IDCategory_Product { get; set; }
        public int IDSales { get; set; }
        public int IDShops { get; set; }
    
        public virtual Category_Products Category_Products { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Shops Shops { get; set; }
    }
}
